name: scmodal
channels:
  - conda-forge
  - pytorch
  - bioconda
  - defaults
dependencies:
  - python>=3.7
  - pytorch>=1.6.0, <=1.13.1
  - scanpy>=1.7.2
  - anndata>=0.7.6
  - pandas=1.1.5
  - numpy>=1.19.0
  - umap-learn>=0.4.6
  - numba>=0.49.1
  - matplotlib<3.7
  - scikit-learn>=1.3.0
  - scipy>=1.10.1 
  - python-annoy>=1.17.1